name: ci

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/ci.yml"
      - "src/**"
      - "pom.xml"
  pull_request:
    branches: [main]

permissions:
  packages: write

concurrency:
  group: ci
  cancel-in-progress: false

jobs:
  build-jvm:
    runs-on: ubuntu-latest
    env:
      MVN: mvn --show-version --batch-mode
    steps:
      - name: jdk11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: login ghcr.io
        uses: docker/login-action@v1.8.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true
      - name: checkout
        uses: actions/checkout@v2
      - name: cache ~/.m2
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: mvn clean compile
        run: $MVN clean compile
#      - name: mvn test
#        run: $MVN test
      - name: mvn package -DskipTests -Dquarkus.container-image.push=true latest
        if: github.ref == 'refs/heads/master'
        run: $MVN package -DskipTests -Dquarkus.container-image.push=true -Dquarkus.container-image.image=ghcr.io/talencyco/quarkus:latest '-Dquarkus.jib.labels."org.opencontainers.image.revision"='$GITHUB_SHA
      - name: mvn package -DskipTests -Dquarkus.container-image.push=true snapshot
        if: github.ref != 'refs/heads/master'
        run: $MVN package -DskipTests -Dquarkus.container-image.push=true -Dquarkus.container-image.image=ghcr.io/talencyco/quarkus:snapshot '-Dquarkus.jib.labels."org.opencontainers.image.revision"='$GITHUB_SHA
